#!/bin/sh -x
#
# generic-startup  plfs emulab startup script
# 24-May-2012  chuck@ece.cmu.edu
#

# redirect all stdout/stderr to log file in /tmp so user can debug errors

exec > /tmp/startup.log 2>&1

#############################################################################
# first, the generic startup stuff
#############################################################################

# sudo /share/probe/bin/linux-fixpart all                                            || exit 1

# create local file system on /dev/sdc (HDD)
#sudo /share/probe/bin/linux-localfs -t ext4 /l0               || exit 1
#sudo /share/probe/bin/linux-localfs -d /dev/nvme0n1 -t ext4 /l0                   || exit 1

#sudo mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 /dev/sda
#mkdir /l0
#sudo mount -o defaults,noatime,nodiratime /dev/sda /l0

#sudo /share/probe/bin/probe-localize-resolv                                        || exit 1

# generate key: ssh-keygen -t rsa -f ./id_rsa
/share/probe/bin/probe-sshkey                                                      || exit 1

#sudo /share/probe/bin/probe-network --big --eth up \
#                                          --ib connected                           || exit 1


setup_dir=$(dirname $(readlink -f $0))

sudo cp ${setup_dir}/limits.conf /etc/security/limits.conf
sudo cp ${setup_dir}/core_pattern /proc/sys/kernel/core_pattern
ulimit -c ulimited

echo "startup complete."
exit 0
