#!/bin/sh -x
#
# generic-startup  plfs emulab startup script
# 24-May-2012  chuck@ece.cmu.edu
#

# redirect all stdout/stderr to log file in /tmp so user can debug errors

exec > /tmp/startup.log 2>&1
#############################################################################
# first, the generic startup stuff
#############################################################################

setup_local_fs()
{
    device=$1
    mount_pt=$2
    sudo mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 ${device}
    sudo mkdir ${mount_pt}
    sudo mount -o defaults,noatime,nodiratime ${device} ${mount_pt}
    sudo chown -R jinlianw:BigLearning ${mount_pt}
}

setup_dir=$(dirname $(readlink -f $0))
echo $setup_dir

sudo cp ${setup_dir}/limits.conf /etc/security/limits.conf
sudo cp ${setup_dir}/core_pattern /proc/sys/kernel/core_pattern
ulimit -c unlimited

setup_local_fs /dev/sdb /l0
setup_local_fs /dev/nvme0n1 /l1
sudo mkdir /datasets
sudo mount -t nfs otto-02:/vol/datasets /datasets

echo "startup complete."
exit 0
